version: '3'

services:
  mysql:
    image: my-mysql-image:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypassword1
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

volumes:
  mysql-data:
